### ISSUE TITLE
Missing 'config' directory breaks installation

### ISSUE THREAD

**Issue by corvidism** [dugwood/clickheat#12]
Hi,
the installation currently doesn't work, because the preliminary check always fails when trying to create `/var/server/www/clickheat/config/temp.tmp` - the 'config' folder doesn't exist in the GitHub code and isn't created anywhere in the process.

I forked the repo and will make a pull request with the fix.

**Comment by corvidism** [comment]
I found a similar bug in the config.php file (`logs` and `cache` folders) and made a new branch, so I made a new pull request.

**Comment by dugwood** [comment]
Thanks @corvidism for your help!

**Comment by corvidism** [comment]
Thanks for merging it in so fast. :)

**Comment by dugwood** [comment]
You're welcome. It's true that the old zip file was including the `config` and `cache` folders. I should have created a `.gitignore` file in those directories.
But that was mostly because of PHP safe mode... happily we don't have it anymore, hooray!
