### ISSUE TITLE
ClickHeat Groups and Domains list not showing

### ISSUE THREAD

**Issue by committedpro** [dugwood/clickheat#17]
We have installed and configured to work on multi-sites and I have checked the logged that, clicks being logging to each domain URL correctly as well. 

And also we have not specified any domain and groups in the configuration page.

**Comment by dugwood** [comment]
Did you tried the debug mode? You just append `#debugclickheat` at the end of your url (where you installed the tracking code), and reload the page. You should see a debug box on the left side. Then click in a blank area (anywhere but on a link). Then paste the result here (remove sensitive information such as your file paths and the like).

**Comment by committedpro** [comment]
Thank you for prompt response, you gesture really appreciated!.

Attached screen shots.

Clicks are working fine.

But I can not able to view domain specific click stats.

Please advise.

**Comment by dugwood** [comment]
Closing for further details to be received by email.

Edit: issue fixed by specifying a default group name.

**Comment by committedpro** [comment]
Hi I have attached 4 screenshots from E-mail, but it seems those were not posted. I did not aware of it.
Now I am attaching here, please check the screenshots.

Clicks are working fine.
But I can not able to view domain specific click stats.

Please advise.

**Comment by committedpro** [comment]
Attach files are not working.
