### ISSUE TITLE
Plugin.json

### ISSUE THREAD

**Issue by Sjoerd** [dugwood/clickheat#18]
I'm trying to install this plugin, but it doesn't work.

I'm getting the following error: Plugin is not valid, it is missing the plugin.json file.

**Comment by dugwood** [comment]
Are you trying to install it through Piwik? This release doesn't support Piwik anymore, you should install it as a standalone software (it works best this way!).

**Comment by Sjoerd** [comment]
Thanks :)

**Comment by dugwood** [comment]
In fact it's supported by: https://plugins.piwik.org/ClickHeat (so the code should be similar).

**Comment by Sjoerd** [comment]
It doesn't work for Piwik 3

**Comment by dugwood** [comment]
Thanks for the heads up, I didn't know there was a Piwik 3 :-) At one point, the idea was to merge ClickHeat in Piwik, but it's never been done (too much work!).
