### ISSUE TITLE
Page screenshot not showing

### ISSUE THREAD

**Issue by doncabreraphone** [dugwood/clickheat#24]
Hello,

I just installed this awesome plugin (11/13/2018) and I don't see the page showing (I assume it will be a screenshot of the page, or an iframe, with an overlay with the heatmaps).

At the moment, it only shows the heatmap alone, but I don't see a screenshot of the page being shown behind the heatmap, so it just shows a gray area and the heatmaps.

Beyond installing the script and configuring it correctly, giving permissions to the /log/ folder, I did nothing else that could have caused this. Could someone shed some light?

Thanks!

Javier

**Comment by dugwood** [comment]
Thanks Javier for reporting this. You're right, it's displayed in an iframe (creating a screenshot would need a huge library, if any is available, or a paying service such as browsershots).

Can you open your browser console (F12 for Chrome, Safari, Firefox), and look for errors in the Console tab. You should have a warning or something like this. It may help understand the issue. So far I can only think about a permission issue of website embedded in an iframe. Highly probable if you use one domain for clickheat and you're installing it on another one.

Can you please share the errors in your console (remove anything you find risky in the text you'll see)?

**Comment by doncabreraphone** [comment]
Hello dugwood!

Thanks for coming back to me!

Yes, you are right, the problem were the domain's permissions with the embedded iframe.

The console told me the error was "blocked loading active mixed content", so I had to force https on the site I wanted to use the script with through .htaccess

Then, I went and changed the url.txt to https on my clickheat installation and it all resolved! The workaround is not mine, by the way. I saw it online, in some forum.

Question: this script records mobile touches as well? (too bad it doesn't records scrolls or mouse movements! But its amazing, even without those!)

**Comment by dugwood** [comment]
I'm glad you fixed it :-)

I didn't think of HTTPS, so thanks for pointing that out!

Mobile touches should be recorded as it triggers the `onclick` event. The only case I can think of which wouldn't record the touch is when you have an `hover` in CSS, which cannot be rendered on touch screens. In this case, you'll have a first touch that enables the `hover` but doesn't triggers `onclick`, then you'll have the tracking on the effective second touch that will click.

Scrolls could be an addition... but I didn't have the time to even rewrite the code in years :-1:
For mouse movements, I think it's too much data to store, with so few interest (I don't care about my mouse position when I read, some users don't even use mouse wheel and go click on the scrollbars to go down the page, a lot of useless information). I know some tools did it back in the days I wrote ClickHeat, but I don't know how it's stored/analyzed. I just remember the demo page to be sooooo slow :-D
