### ISSUE TITLE
Log file documentation

### ISSUE THREAD

**Issue by hubyhuby** [dugwood/clickheat#25]
Thanks for this cool software.
Is there a documentation / explaination of the log file format?
Is it possible to atribute a unique ID to each visitor ? Especially for usability testings scenarios.
Is it possible to have a time stamp ?

Current Log output :  

151|147|2133|chrome|1
148|102|2133|chrome|1
17|63|360|chrome|1
126|142|360|chrome|1
22|47|360|chrome|1
128|109|360|chrome|1
32|26|360|chrome|1
145|143|360|chrome|1
38|37|360|chrome|1
93|203|360|chrome|1
38|37|360|chrome|1
143|111|360|chrome|1
45|48|360|chrome|1
108|162|360|chrome|1

**Comment by dugwood** [comment]
Hello @hubyhuby, I don't even remember the format :-)

There's no timestamp as everything is stored as a daily basis (the file name includes the date).

For the format it's:
x|y|width|browser|button
(where button is 1 for left, 2 for right, and 3 for middle IIRC)
Source: https://github.com/dugwood/clickheat/blob/master/click.php#L168

You may add a unique ID for each visitor with a cookie, but it's a specific request that I won't have time to code... But if you do it, I may add it for everyone. Another option I can think of: if you know the scenario beforehand, you may use a dedicated group for this. Say you have a page.html with 2 scenarii (A & B) based on a user settings (perhaps a cookie), then you can track with `clickHeatGroup = 'page-scenario-a` and `clickHeatGroup = 'page-scenario-b`.
