### ISSUE TITLE
Can't see the groups and domain names 

### ISSUE THREAD

**Issue by subiz1** [dugwood/clickheat#26]
I Installed and configured it. But I'm not able to see my groups and websites. Moreover, when I place the javascript code and run in degub mode it shows me axis.
![ss](https://user-images.githubusercontent.com/49172328/57482353-d9349c80-72bd-11e9-8fd8-c0b24b4bf8ee.png)

**Comment by dugwood** [comment]
Hello, you have set a list of allowed domains, hence all other domains are forbidden.

Here, you're running on `localhost`, which is forbidden. Either add `localhost` to the list of allowed domains, or remove the whole list of allowed domains.
