### ISSUE TITLE
Website Image Shows but no heat map is overlaid 

### ISSUE THREAD

**Issue by yatesy2380** [dugwood/clickheat#28]
The script is logging the clicks properly.  I have tested the debugging. My sites screenshot shows if I click the left mouse button on my image and then try to drag it, I get a little image, like a thumbnail about the mouse mounted which is grey and this shows the where the clicks are. It's like the heatmap is behind my website image.

Any help would be appreciated, I have also tried messing about with the transparency but still can't see anything. 

Many thanks

Michael

**Comment by dugwood** [comment]
@yatesy2380 most of the time, that's because of forbidden iframe embedding. Such as header `X-Frame-Options`.

Can you open your console and look what error may show up? This will help solve your issue.

**Comment by yatesy2380** [comment]
Thank you for your reply :). 

This is what appears on the console of Chrome. 

![image](https://user-images.githubusercontent.com/75327042/100786298-dbaf9780-3409-11eb-948f-47baaf38586e.png)

I'll have a play with it see if there are any settings on my host which may prevent iframes from loading.

**Comment by dugwood** [comment]
@yatesy2380 sorry, I've misread: your issue is not the website, but the map not showing up.

Can you send me an access to the `user` account (not the `admin` account) on my email: yvan -at- dugwood -dot- com? I'll see what's going on. I don't see any issues with the console so far.

**Comment by dugwood** [comment]
Issue to be fixed: `backdrop-filter` impacts all parents in the DOM, I'll change the `cleanIframe()` function to remove all `backdrop-filter` effects.

**Comment by dugwood** [comment]
@yatesy2380 it should be fixed with new release: https://github.com/dugwood/clickheat/releases/tag/1.15

Thanks for your help on this :smile:

**Comment by yatesy2380** [comment]
Hello sorry to be a pain but I've just updated it all and it's doing the exact same thing. After I updated it and it didn't' work, I then deleted it all and installed the new version from fresh but its still doing the same thing. 

https://www.youtube.com/watch?v=nyStIakwpzA

There is no rush for you to fix this, thank you 👍

**Comment by dugwood** [comment]
@yatesy2380 can you try the https://github.com/dugwood/clickheat/releases/tag/1.16 release please?

You don't need to delete the whole code, just overwrite it.

If it's still not working as expected, I'll make a copy of your website to test it (I can't use it directly because of X-Frame-Options).
