### ISSUE TITLE
Safari Bug

### ISSUE THREAD

**Issue by volomike** [dugwood/clickheat#7]
In the latest Safari, we're seeing that this fails with this error:

"can't find variable initClickHeat"

It's like there's a call to initClickHeat() before the Javascript has finished loading. The problem doesn't fail in Firefox, Chrome, or IE. Just Safari.

**Comment by dugwood** [comment]
Thanks for your report.

I've just tried on a Safari 10.0 on a Mac, it seems to work in debug mode:
https://www.dugwood.com/clickheat/index.html#debugclickheat

Can you try this link and click anywhere but on a link to see if it's working? If it's not working, please send me the version you're using, for Safari and ClickHeat (now ClickHeat has only the github repository, so it will be 1.14, so just tell me if you downloaded it recently on github).

**Comment by dugwood** [comment]
Just saw the same issue in my logs. Can't reproduce on my Safari...

Do you have an ad-blocker or something like this? If you open the development tools, what errors do you see?
