### ISSUE TITLE
Click saved in log but not displayed

### ISSUE THREAD

**Issue by mtx-z** [dugwood/clickheat#8]
Hello !
I'm trying to use Clickheat to get a heatmap of my website. 
All seems good, Ajax request send back a "Ok" and all click are stored in log file.

But in clickHeat admin, nothing is displayed. Also, i cannot choose any group/site in the top-left select (wich is empty). 

Any idea why ? Maybe i dont understand the "group" thing... 

thanks !

**Comment by dugwood** [comment]
Hello !

Did you try the debug mode? Just append #debugclickheat to the end of the url, then reload the page.

Then click in a blank area (anywhere but on a link). You should then see the «group» where the click was saved.

Also note that sometimes there's some caching of the images, so the clicks may not be live (but should be...).

**Comment by mtx-z** [comment]
Hello !
Cool debug system, it give me some more informations.

The group name seems to be created from URL, and i got the error "forbiden group, check config".
How can i manage to create groupe that will match ? Is wildcard like domain.com/* possible ?

Thx a lot !

**Comment by dugwood** [comment]
Either:
- add a group when you generate the javascript tracker, and then list all groups in your config
- or remove the group filter

Clearly, the risk of data poisoning is close to 0%. It's important on my demo domain, because people know that there are other people who will see their input (I had a lot of «drawings» on demo heatmap back in the days, when there was no group/click/source restriction).

There's no wildcard of domain/*, because there are 2 filters:
- allowed groups
- allowed domains

You may set only the domain filter, if you want. Ignore the group filter unless you see some people creating bad data.

**Comment by mtx-z** [comment]
So, to ignore the "groupe", i just let the input empty, and fill the domain only. This way all click from the domain will be recorded ?

**Comment by dugwood** [comment]
Right. And test in the debug mode, so you'll see if it's okay or not :-)

**Comment by mtx-z** [comment]
Just tested by removing the "group" settings in configuration. Using debug mode, all seems ok, but no click to view...
Heres some screenshots : 

Debug view: [here](http://img11.hostingpics.net/pics/464207screen1.png)
Dashboard: [here](http://img11.hostingpics.net/pics/694371screen2.png)
Config: [here](http://img11.hostingpics.net/pics/251218screen3.png)

It seems that system still save a "group" value. 
Also, "update" button tell me 1.14 is not the latest, but downloaded yesterday from Git zip.

I don't get why i have nothing...

**Comment by dugwood** [comment]
I've migrated the code from the old domain (labsmedia) to my new one... a lot of work should be done on Clickheat, but I don't have time for this... So don't worry about the release, as long as you download from github master, it's the good one :-)

I can't see any issue there for the tracking. Did you remove your own IP by clicking on «Enregistrer mes clics»?

Can you test on dugwood.com (you can append the #debugclickheat too), to see the behaviour? And look at the source code of dugwood.com, to see if you have something similar.

Are you on HTTPS website?

**Comment by mtx-z** [comment]
Yes it works !!!
I missed the JS "site" parameter, it was empty. 
Now it's working great :D All clicks are 10-20px below of real point, but is great !

Thanks a lot for your support, and for clickheat !

**Comment by dugwood** [comment]
Clicks should be vertically correct... do you have something like a top fixed menu?

You should also set the layout by clicking the icon next to the group selector. That helps positionning clicks when your website is fixed in width (most of websites are).

Happy to help :-)
